---
title: "SiteMapping_Honors_Nov6"
output: html_document
date: "2023-11-06"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#Open all necessary packages 
library(tidyverse)
library(RColorBrewer)
library(rgdal)
library(sp)
library(ggspatial)
library(sf)
library(grid)
library(magrittr)
library(ggpubr)
library(ggpmisc)
library(stringr)
library(lemon)
library(cowplot)
library(rerddap)
library(dplyr)


#####PVR SITES#####

# ## Set working directory
setwd("/Users/alyssaplayer/Desktop/Honors/HonorsR")


# Read in sites file=
data_PV <- read.csv("PV_Stars_Urchins2024-02-09.csv")


##Burial Grounds, Cape Point not showing up as on the Map - Should be green triangles. 

pvr_control_sites <- c(#"Hawthorne Reef",
                   "Honeymoon Cove",
                   "Lunada Bay",
                   #"Resort Point",  
                   "Rocky Point South",
                   "Rocky Point North",
                   "Ridges North")

pvr_impact_sites <- c("KOU Rock",
                      "Old 18th",
                      "Burial Grounds",
                      "Cape Point",
                      "3 Palms West",
                      "3 Palms East",
                      "Bunker Point")

MPA_control_sites <- c(#"Hawthorne Reef",
                   "Marguerite Central",
                   "Albondigas",
                   "Marguerite East",  
                   "Golden Cove",
                   #"Resort Point",
                   "Portuguese Bend")

MPA_impact_sites <- c("Long Point East",
                      "120 Reef",
                      "Abalone Cove Kelp West",
                      "Long Point West",
                      "Old Marineland",                 
                      "Point Vicente West",
                      "Portuguese Point")

both_control_sites <- c("Hawthorne Reef",
                        "Resort Point") 



sites <- data_PV %>%
  filter(!is.na(Site), !is.na(Latitude), !is.na(Longitude), Site != "Marguerite West",
                                                            Site != "Christmas Tree Cove",
                                                            Site != "Point Fermin" ,
                                                            Site != "Whites Point" ,
                                                            Site != "Ridges South",
                                                            Site != "Cairns", 
                                                            Site != "Underwater Arch") %>% 
  group_by(Site) %>%
  dplyr::summarize(Mean_Latitude = mean(Latitude), Mean_Longitude = mean(Longitude)) %>%
  mutate(MPA_PVR = case_when(Site %in% MPA_control_sites ~"MPA",
                             Site %in% MPA_impact_sites ~"MPA",
                             Site %in% both_control_sites ~"Both",
                              TRUE ~ "PVR")) %>%
         mutate(Site_Type = case_when(Site %in% pvr_control_sites ~ "Control",
                               Site %in% MPA_control_sites ~ "Control",
                               Site %in% both_control_sites ~"Control",
                               TRUE ~ "Impact"))

```


<!-- #Set the theme of the map  -->
```{r}
map_theme <- list(theme(panel.grid.minor = element_blank(),
                        panel.grid.major = element_line(color = "grey80", 
                                                        linetype = "dashed", linewidth = 0.5),
                        #plot.background = element_rect(fill="aliceblue"),
                        panel.border = element_rect(colour = "black", fill=NA, linewidth = 1),
                        axis.line = element_blank(),
                        #axis.text.x = element_blank(),
                        #axis.text.y = element_blank(),
                        axis.ticks = element_blank(),
                        #axis.title.x = element_blank(),
                        #axis.title.y = element_blank(),
                        #legend.title=element_blank(),
                        legend.background = element_rect(fill = "transparent"),
                        legend.key = element_rect(fill = "transparent"),
                        legend.text = element_text(color = "black"),
                        legend.position = c(0.13,0.30),
                        plot.title = element_text(size=22)))
```

```{r Download maps and create spatial features}
#Global Administrative Boundaries for US and Mexico
# level 0 = no boundaries, level 1 = states, level = 2 counties
usa <- raster::getData("GADM", country="USA", level=1)

# Subset for California Only
california <- subset(usa, usa$NAME_1 == "California")
# convert CRS from WGS84 to UTM zone 11 N to minimize distortion
california <- spTransform(california, 
                          CRS("+proj=utm +zone=11 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0"))   
california <- st_as_sf(california) #converts to sf object
rm(usa)
# Configure sites
sites_all <- sites # creates a new object to transform into a spatial points data frame
 coordinates(sites_all) <- ~Mean_Longitude+Mean_Latitude # defines coordinates
proj4string(sites_all) <- CRS("+proj=longlat +datum=WGS84") # defines original projection (WGS84)
Sites_Map_All <-spTransform(sites_all,  # transforms projection from WGS84 to UTM Zone 11N
                        CRS("+proj=utm +zone=11 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0"))

# all sites where SWATH data were collected
Sites_Map_All <- data.frame(sites_all) %>%
              select(-"Site",-"Mean_Latitude",-"Mean_Longitude" ) %>%
              distinct()
# 
 # Set coordinates for map of PV
coords_pv<- coord_sf(xlim = c(-118.25, -118.5), ylim = c(33.65, 33.82), crs = "+init=epsg:4326 +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0", expand = F)
 
# Set coordinates for map of CA
coords_ca<- coord_sf(xlim = c(-125, -113.5), ylim = c(32, 43), crs = "+init=epsg:4326 +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0", expand = F)

# # Set up the coordinate limits for the map of PV
# coords_pv <- coord_sf(xlim = c(-118, -118.5), ylim = c(33.5, 34), expand = FALSE)
# 
# # Set up the coordinate limits for the map of CA
# coords_ca <- coord_sf(xlim = c(-125, -113.5), ylim = c(32, 43), expand = FALSE)

california <- st_as_sf(california)
```

```{r Read in MPA Shapefile}

MPA_shp <- read_sf(dsn = ".", layer = "California_Marine_Protected_Areas_[ds582]")

MPA_shp <- MPA_shp %>%
               filter(NAME == "Abalone Cove SMCA"| NAME == "Point Vicente SMCA (No-Take)")

```


```{r}

#ggplot(sites, aes(Mean_Latitude, Mean_Longitude)) + geom_point()

PV_sites_plot <- ggplot() +
  geom_sf(data = MPA_shp, alpha = 0.15, linewidth = 0, aes(fill = Type))+ 
  scale_fill_manual(values = c("SMCA" = "mediumpurple4", "SMCA (No-Take)" = "red"))+
  geom_sf(data = california, fill = "antiquewhite", linewidth = 0.3) +   
  coord_sf(xlim = c(-118.30, -118.5), ylim = c(33.65, 33.80), crs = "+init=epsg:4326 +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0", expand = F) +
  geom_point(data = sites, aes(x = Mean_Longitude, y = Mean_Latitude, shape = Site_Type, color = MPA_PVR), size = 3) +
  scale_shape_manual(values = c("Control" = 16, "Impact" = 17)) +
  scale_color_manual(values = c("MPA" = "darkseagreen", "PVR" = "cadetblue3", "Both" = "red")) +
  labs(color = "Site_Type") +
  xlab("") + ylab("") +
  annotate(geom = "text", x = -118.355, y = 33.755, label = "PALOS VERDES PENINSULA", angle = -45,
               fontface = "italic", color = "grey22", size = 2.75)+
  annotation_scale(location = "bl", width_hint = 0.5) +
  annotation_north_arrow(height = unit(0.75, "in"),
                         width = unit(0.75, "in"),
                         location = "bl", which_north = "true",
                         pad_y = unit(0.5, "in"),
                         style = north_arrow_fancy_orienteering) +
  theme(panel.grid.minor = element_blank(),
        panel.border = element_rect(colour = "black", fill = NA, linewidth = 1),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        legend.background = element_rect(fill = "transparent"),
        legend.key = element_rect(fill = "transparent"),
        legend.text = element_text(color = "black", size = 8),
        legend.position = "bottom",
        legend.title = element_text(size = 9),
        plot.margin = margin(0, 0.75, 0, 0, "cm"))

PV_sites_plot
      # guides(fill = guide_legend(override.aes=list(shape=21))) +# guides(fill = guide_legend(override.aes=list(shape=21))) +# guides(fill = guide_legend(override.aes=list(shape=21))) +
      # annotate regions  
    PV_map <- sites
    ggsave("PV sites.jpg", height = 6, width = 8, dpi = 300)
    
```



```{r}
    
map_bounding_box <- data.frame(long = c(-118.25, -118.25, -118.5, -118.5, -118.25),
                                   lat = c(33.65, 33.82, 33.82, 33.65, 33.65))
    
    locator_map <- ggplot(data = california) +
      geom_sf(fill = "antiquewhite", lwd = 0.25) +
      coords_ca +
      xlab("") + ylab("") +
      annotate(geom = "text", x = -119, y = 37, label = "CALIFORNIA", angle = -45,
               fontface = "italic", color = "grey22", size = 2.75) +
      geom_rect(data = map_bounding_box,
                mapping = aes(xmin = -118, xmax = -118.6, ymin = 33.6, ymax = 34.0),
                fill = NA, color = "red", size = 0.25) +
      theme(panel.grid.minor = element_blank(),
            panel.grid.major = element_line(color = "grey90", linetype = "dashed", size = 0.5),
            panel.background = element_rect(fill = "grey90"),
            plot.background = element_blank(),
            panel.border = element_rect(colour = "black", fill = NA, size = 1),
            axis.line = element_blank(),
            axis.text.x = element_blank(),
            axis.text.y = element_blank(),
            axis.ticks = element_blank(),
            axis.title.x = element_blank(),
            axis.title.y = element_blank())
locator_map
ggsave("Locator_Map.jpg", height = 2.5, width = 1.5, dpi = 300)

# PV_Sites_final <- ggdraw() +
#   draw_plot(SCB_map) +
#   draw_plot(locator_map, x = 0.63, y = 0.65, width = 0.18, height = 0.29)


#ggsave(filename = "PV_Sites.jpg", width = 8, height = 6, device='jpeg', dpi=700)
```

